#!/usr/bin/env bash
#Bash scripts to display informatiom about a subdomain
# shellcheck disable=SC2086

display_info ()
{
 	record=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}');
	ip=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}');
	echo "The subdomain $2 is a $record record and points to $ip";
}

if [ $# = 1 ]
then
	display_info "$1" "www";
	display_info "$1" "lb-01";
	display_info "$1" "web-01";
	display_info "$1" "web-02";
elif [ $# = 2 ]
then
	display_info "$1" "$2";
fi
