#!/usr/bin/env bash
#automate nginx configuration
sudo apt-get -y update
sudo apt-get -y  install nginx
sudo chmod a+w /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
