#!/usr/bin/env bash
#automate nginx configuration
sudo apt-get -y update
sudo apt-get -y  install nginx
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name _;/a \\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
sudo service nginx restart
