#!/usr/bin/env bash
#automate nginx configuration
sudo apt-get -y update
sudo apt-get -y  install nginx
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i '/server_name _;/a \\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n\terror_page 404 /var/wwww/html/404.html' /etc/nginx/sites-available/default
sudo service nginx restart
