#!/usr/bin/env bash
#install and configure load balancer
apt-get -y update
apt-get -y upgrade
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get -y install haproxy=2.8.\*
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo -e "\nfrontend webapp\n\tbind *:80\n\tmode http\n\tdefault_backend webservers" >> /etc/haproxy/haproxy.cfg
echo -e "\nbackend webservers\n\tbalance roundrobin\n\tserver 264401-web-01 3.86.7.132:80 check\n\tserver 264401-web-02 54.167.172.117:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
