#!/usr/bin/env bash
#install and configure load balancer
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*
sudo echo -e "\nfrontend webapp\n\tbind *:80\n\tdefault_backend backend_servers\n" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\nbackend backend_servers\n\tbalance roundrobin\n\tserver 264401-web-01 3.86.7.132:80 check\n\tserver 264401-web-02 54.167.172.117:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
