#!/usr/bin/env bash
# displays To infinity and beyond indefinetly
echo "$$" > /var/run/myscript.pid
while ((1))
do
	echo "To infinity and beyond"
	trap 'echo "I hate the kill command" && rm /var/run/myscript.pid && kill $$' 15
	trap "echo 'Y U no love me?!'" 2
	trap 'rm /var/run/myscript.pid && kill $$' 3
done
